### PR TITLE
Add CvssSuite module on all classes

### LINKED ISSUE #11: Unscoped classs
### Subject of the issue

I already have a class Cvss on my project and I have a conflit with the Cvss class of this gem because all class are not scope on a CvssSuite module.

https://github.com/siemens/cvss-suite/blob/master/lib/cvss_suite/cvss.rb#L14

### Fix

I will work on a PR to fix this.

### PR DESCRIPTION
**Pull request by fwininger**
## Proposed changes

Resolve #11 

## Types of changes

- [x] A module everyware

### CODE REVIEW

**Comment by fwininger** [comment]
You can use the option "hide space change" to simplify the review : 

https://github.com/siemens/cvss-suite/pull/16/files?diff=split&w=1

**Comment by oliverhamboerger** [comment]
I just tested it and it looks good. This change isn't a breaking change as long as people only use CvssSuite and not e.g. Cvss31 directly right?

Still works:
cvss = CvssSuite.new('string')

Won't work anymore (without any code change):
cvss = Cvss31.new('string', 'version')
This would need to be CvssSuite::Cvss31.new('string', 'version') to work. Or you could include the whole namespace.

If you agree I'll put it in the changelog like this.

**Comment by fwininger** [comment]
This is exactly it. I did not note this as a breaking change because in all the examples include in the readme we only use the CvssSuite method.

**Comment by fwininger** [comment]
> Won't work anymore (without any code change):
> cvss = Cvss31.new('string', 'version')

I'dont understand why we need to have a 'version' parameter ?

I think that Cvss31 class can implement a method : 

```ruby
def version
  "3.1"
end
```

I'm surprised we can do : 

```ruby
cvss = Cvss31.new('CVSS:3.1/AV:P/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:H/E:H/RL:U/RC:U', 'hello-kitty)
valid = cvss.valid?   # true
cvss.version          # hello-kitty
```

**Comment by oliverhamboerger** [comment]
Good point, will merge your PR and add the change regarding the version method

**Pull request merged**
