### PR TITLE
Add build badge and update travis.yml

### PR DESCRIPTION
**Pull request by adamrdavid**
## Proposed changes

Get Travis CI working so that we can have those nifty commit status markers and a build status badge on the readme.  This might also allow us to remove the check boxes for passing tests in the pull request template

Examples:
screen shot 2018-12-10 at 5 21 23 pm
screen shot 2018-12-10 at 5 20 56 pm
screen shot 2018-12-10 at 5 29 37 pm

## Types of changes

What types of changes does your code introduce to CvssSuite?

None of the below, only a github/CI change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._

- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
This will require someone with an owner role to enable Travis CI for the repo here: https://travis-ci.org/siemens/cvss-suite

### CODE REVIEW

**Comment by oliverhamboerger** [comment]
I will take it look it at, but first I need to take a detailed look at Travis before activating it.

**Comment by adamrdavid** [comment]
Now with github actions I think it would be better to use that.  examples: 
https://github.com/bugcrowd/vrt-ruby/actions
https://github.com/bugcrowd/vulnerability-rating-taxonomy/runs/383957128

**Comment by oliverhamboerger** [comment]
I also thought about Actions but didn’t have time to take a closer look. Maybe will do in the next weeks can’t promise though.

**Comment by adamrdavid** [comment]
Okay 👍 I'm going to close this out as not relevant anymore.

**Pull request closed without merging**
